### ISSUE TITLE
Is the latest commit the same as the one you were using in your youtube video

### ISSUE THREAD

**Issue by 0rdinal** [cokwa/F4MP#2]
I managed to get a server running and actually got someone to connect from a remote location using my public IP. However, a few things shown in your videos did not seem to work, especially when it came to the workshop and player animation. Is this repo the latest version of the code?

Obviously this is still in very early stages so I'm not expecting anything, but if you do have a later version, I urge you to upload it. I really hope you continue working on this project as you have done so much in just a few months.

**Comment by cokwa** [comment]
Animations "properly" work only on third-person for now. And I do remember that I messed up the settlement building sync and then left it so 'cause I wanted to work on something else. There are definitely code for debugging and stuff so it's definitely not suitable for a proper playthrough. Guess I should have made a stable branch, huh?

**Comment by 0rdinal** [comment]
A stable branch would be a good idea. I managed to build the binary successfully using msbuild.

Another thing I noticed was, from what I could tell, things would get out of sync as the server recieved more instructions than it could handle in a second. So the other person would do something and it would take upwards of a minute to happen for the other user. As well as the audio sync seemed to be broken and would play mechanist radio and silver shroud soundbites randomly.

If you want, I'd be more than happy to be your tester if you continue development, so that you know it works in multiple environments.

**Comment by cokwa** [comment]
That'd be great. As for the random radio broadcast and stuff, it's the shitty dialogue sync. I manually disabled all the lines from the main game but then I haven't got rid of the DLC ones(partially since I have no DLC in my game). The out-of-sync problem.. yeah. It's because I don't really have any real knowledge on network libraries or just networking in general. I will eventually have to fix it but it's in low priority for my list.

**Comment by 0rdinal** [comment]
Understandable, I'll close the issue. All I can suggest is look in async for the server if you aren't using it already
