### ISSUE TITLE
press f`1 crash game

### ISSUE THREAD

**Issue by CoolAugustusOfficial** [cokwa/F4MP#3]
>:( fix

**Comment by 0rdinal** [comment]
Load Order? 
F4MP Config settings?

**Comment by CoolAugustusOfficial** [comment]
no mods.

localhost in the fallout4 directory

my friends ip in the server connect .txt in documents

**Comment by 0rdinal** [comment]
So your friend is hosting? And you have the esp and dll installed? Other than that, ensure your friend has port forwarded properly. Direct him to the readme just posted

**Comment by CoolAugustusOfficial** [comment]
um yes!, i have tjhe esp instllaed, the DLL in the f4se plugins folder. 

it just auto crashes after pressing F1, nothing else hpapens. ill tell him to prot forward though

**Comment by 0rdinal** [comment]
I'm going to close this issue, for now. If you are still having issues, open a new one using the template.
