### ISSUE TITLE
Crash to desktop when loading a save with certain characters

### ISSUE THREAD

**Issue by nodeofgithub** [cokwa/F4MP#5]
**Describe the bug**
CTD when loading a save created while F4MP active

**To Reproduce**
1. ~~With no mods loaded~~ With F4MP already loaded, create a new save
2. Restart game
3. Load save

**Expected behavior**
Save should load without a CTD

**Files**
 - [config.txt](https://github.com/cokwa/F4MP/files/4912706/config.txt)
 - [F4MP.log](https://github.com/cokwa/F4MP/files/4912708/F4MP.log)
 - [server_config.txt](https://github.com/cokwa/F4MP/files/4912710/server_config.txt)

**Load Order**
```
Fallout4.esm=1
f4mp.esp=1
```

**Additional context**
Attaching a debugger shows that the following exception is raised during the crash:
```
(3bec.1fc4): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** WARNING: Unable to verify checksum for C:\Games\Fallout 4\Data\F4SE\Plugins\f4mp.dll
f4mp!F4SEPlugin_Load+0xf2a8:
000001dd3c0042b8 83781000 cmp dword ptr [rax+10h],0 ds:0000000000000010=????????
```

**Comment by 0rdinal** [comment]
Not reproducible while performing the following steps:

1. Open fallout 4 from steam while no mods are installed
2. Start new game, exit Vault 111, save game, quit.
3. Install mod using mod manager
4. Start game using `f4se_loader.exe`
5. Load existing save

Please ensure your load order is the one shown in your issue and that you have no other mods installed.

**Comment by 0rdinal** [comment]
I'm going to close this issue for now, it can be re-opened if successfully reproduced.

**Comment by nodeofgithub** [comment]
Some more crash info.


![crashonload](https://user-images.githubusercontent.com/4393110/87885914-4a6ef400-ca19-11ea-971a-e913516285b1.png)
